name: Catch Runner Ping
on:
  repository_dispatch:
    types: [forgejo_ping] # Must match the event_type sent from Forgejo

jobs:
  print-ping:
    runs-on: ubuntu-latest # Free GitHub cloud runner
    steps:
      - name: Read Message from Forgejo
        run: |
          echo "Connection Successful!"
          echo "Payload Received: ${{ github.event.client_payload.message }}"
